COMP 4448: Data Science Tools II
Assignment 1
Brenda Woodard

In [30]:
import numpy as np
import pandas as pd
import sklearn
import sklearn.preprocessing 
from sklearn.preprocessing import (StandardScaler, MinMaxScaler, LabelBinarizer)
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction import DictVectorizer
from sklearn.pipeline import Pipeline
import scipy
from scipy import stats

In [2]:
# Question 1

# Read the boston dataset csv files into Python
bw1 = pd.read_csv('boston_weather_1.csv')
bw2 = pd.read_csv('boston_weather_2.csv')
bw3 = pd.read_csv('boston_weather_3.csv')
bw4 = pd.read_csv('boston_weather_4.csv')
w_var = pd.read_csv('more_weather_variables.csv')

# Assign the datasets to DataFrames
boston_1 = pd.DataFrame(bw1)
boston_2 = pd.DataFrame(bw2)
boston_3 = pd.DataFrame(bw3)
boston_4 = pd.DataFrame(bw4)
more_variables = pd.DataFrame(w_var)
print(more_variables.head())

# Combine or concatenate the DataFrames, boston_1, boston_2, boston_3, and boston_4 and assign the results to a DataFrame 
# The four datasets should be combined vertically since they have the same variable names.
merge1_2 = pd.concat([boston_1, boston_2])
merge2_3 = pd.concat([merge1_2, boston_3])
combined_boston = pd.concat([merge2_3, boston_4])

# Horizontally merge, join or concatenate the combined_boston and more_variables DataFrames 
boston_data = pd.concat([combined_boston, more_variables.set_index(combined_boston.index)], axis = 1)

# Print the first five rows of the boston_data, and the last five rows of the boston_data. 
print(boston_data.head(5))
print(boston_data.tail(5))

# print out the shape of the boston_data. 
print(boston_data.shape)

# Check the boston_data to verify how many missing data points exist under each column. 
boston_data.isnull().sum()

# Drop the rows or instances that contain any missing data and assign the resulting DataFrame to a variable called 
clean_boston_data = boston_data.dropna(axis = 0)

# Check for missing data again to ensure there is no missing data in the clean_boston_data.
print(clean_boston_data.isnull().sum())

# Print the shape of the clean_boston_data
print(clean_boston_data.shape)

# Format all the column names to lowercase and include underscore between column names that consist of two words. 

# Reassign the DataFrame with the formatted column names to the same variable
clean_boston_data = clean_boston_data.rename(columns = {'meanTemp':'mean_temp', 
                                                       'TotPrecip':'tot_precip',
                                                       'TotSnow':'tot_snow',
                                                       'Max24hrPrecip':'max_24hr_precip',
                                                       'Max24hrSnow':'max_24hr_snow',
                                                       'Month':'month', 
                                                       'Year':'year',
                                                       'LowTemp':'low_temp',
                                                       'HighTemp':'high_temp',
                                                       'WarmestMin':'warmest_min',
                                                       'ColdestHigh':'coldest_high',
                                                       'AveMin':'ave_min',
                                                       'AveMax':'ave_max'})

# Print or output the columns of the clean_boston_data DataFrame. 
print(clean_boston_data.columns)

# Select or slice all data from the clean_boston_data DataFrame, except the data where the Year is 1930. 
excluding_1930 = clean_boston_data[~(clean_boston_data.year==1930)]

# Using the excluding_1930 DataFrame, output the first 20 unique values in the Year column.
print(excluding_1930['year'].unique()[:20])

# Select the data from the clean_boston_data where the Year is 1995 AND the high_temp is greater than or equal to 90.
# Output or display the whole selected data.  
print(clean_boston_data[(clean_boston_data.year==1995)&(clean_boston_data.high_temp>=90)].dropna())

# Select the data from the clean_boston_data where the Year is 1995 OR the high_temp is greater than 89. 
# Output or print the first 20 rows of the selected data. 
x = clean_boston_data[(clean_boston_data.year==1995)|(clean_boston_data.high_temp>89)].dropna()
print(x.head(20))

   meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow
0      21.0       2.72    24.8           0.74         6.7
1      27.6       4.11    32.5           1.01        12.2
2      39.3       3.72      11           1.15           6
3      45.1       5.68       2           1.19           2
4      54.6       5.26       0           3.23           0
   Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
0      1  1920     -8.0      48.0        37.0         12.0    12.5    29.5   
1      2  1920     -7.0      52.0        34.0         16.0    20.6    34.6   
2      3  1920     10.0      72.0        45.0         25.0    30.5    48.0   
3      4  1920     26.0      67.0        46.0         37.0    38.0    52.1   
4      5  1920     36.0      86.0        61.0         45.0    47.5    61.8   

   meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
0      21.0       2.72    24.8           0.74         6.7  
1      27.6       4.11    32.5           1.01        12.2  
2  

In [3]:
# Question 2 

# Read the student_data file provided into Python
# The data shows the different midterm scores of students in math, reading & science, & their favorite ice cream flavors. 
data = pd.read_excel('student_data.xlsx')

# Drop the first empty column in Python and assign the DataFrame to a variable student_data.  
student_data = data.drop('Unnamed: 0', axis = 'columns')
student_data = student_data.rename(columns = {'science ':'science'})

# Select the data in the ice_cream_flavor column, convert the flavors to a numpy array, assign it to a var called flavor
flavor = np.array(student_data.ice_cream_flavor)

# From the student_data, select math, reading & science scores all at once, convert to a numpy array, assign to var scores 
scores = np.array(student_data[['math','reading','science']])

# Print the data in the flavor and scores arrays.
print(flavor)
print(scores)

# Use the scores & flavor arrays to slice out the scores where the flavor is chocolate only. 
f = [flavor=='chocollate ']
print(f)

s = scores[[1,5,8,9,13]]
print('Chocolate Only', s)

# Use the scores and flavor arrays to slice out the scores where the flavor is chocolate OR vanilla. 
s2 = scores[[0,1,2,5,6,7,8,9,10,13,14,15]]
print('Chocolate or Vanilla', s2)

# Use the scores and flavor arrays to slice out the scores where the flavor is not chocolate (you can use the “~ “sign). 
s3 = scores[[3,4,11,12]]
print('Everything But Chocolate', s3)

# Slice out all math and reading scores where the flavor is chocolate, then compute the mean of math and reading scores for
# this subset (you can use the .mean() method on the array and specify the axis parameter value appropriately). 
scores2 = np.array(student_data[['math','reading']])
s4 = scores2[[1,5,8,9,13]]
print('Math & Reading Scores for Chocolate Only', s4)

s4.mean(axis = 0)

['vanilla' 'chocollate ' 'vanilla' 'strawberry ' 'strawberry '
 'chocollate ' 'vanilla' 'vanilla' 'chocollate ' 'chocollate ' 'vanilla'
 'strawberry ' 'strawberry ' 'chocollate ' 'vanilla' 'vanilla']
[[ 90  82  90]
 [100  73  92]
 [ 80  92  95]
 [ 95 100  82]
 [ 90  79  81]
 [ 90  90  90]
 [100  89  91]
 [ 80  85  79]
 [ 85  99  85]
 [100  73  92]
 [ 80  92  95]
 [ 95 100  82]
 [ 90  79  81]
 [ 86  92  90]
 [100  89  89]
 [ 83  95  79]]
[array([False,  True, False, False, False,  True, False, False,  True,
        True, False, False, False,  True, False, False])]
Chocolate Only [[100  73  92]
 [ 90  90  90]
 [ 85  99  85]
 [100  73  92]
 [ 86  92  90]]
Chocolate or Vanilla [[ 90  82  90]
 [100  73  92]
 [ 80  92  95]
 [ 90  90  90]
 [100  89  91]
 [ 80  85  79]
 [ 85  99  85]
 [100  73  92]
 [ 80  92  95]
 [ 86  92  90]
 [100  89  89]
 [ 83  95  79]]
Everything But Chocolate [[ 95 100  82]
 [ 90  79  81]
 [ 95 100  82]
 [ 90  79  81]]
Math & Reading Scores for Chocolate Only [[100  73]

array([92.2, 85.4])

In [4]:
# Question 3

# Imagine that you wanted to use the student_data in question 2a to make predictions such that the ice_cream_flavor, math & 
# reading columns are input variables and science column is the output variable you want to predict. 

# Use the LabelBinarizer() to transform the ice_cream_flavor column in the student_data to dummy variables
x = student_data.ice_cream_flavor
label_binarizer = LabelBinarizer()
dummy_vars = label_binarizer.fit(x).transform(x)

# join these dummy variables to the student_data & drop the original ice_cream_flavor column. Reassign the resulting 
# DataFrame to a variable called student_data_1. 
student_data_1 = student_data.drop('ice_cream_flavor', axis = 'columns')
student_data_1['Dummy Vars'] = [i for i in dummy_vars]

# Print out the entire dataset
print(student_data_1)

# Extract the math, reading and science scores & use the StandardScaler() class in the sklearn.preprocessing module to 
# standardize these scores
std_sc = StandardScaler()
s_data_1 = student_data.drop('ice_cream_flavor', axis = 'columns')
print(s_data_1)

std_data = std_sc.fit(s_data_1).transform(s_data_1)
print(std_data.std(axis=0))

# Merge the standardized scores to the dummy variables, and call the resulting DataFrame student_data_std. 
# student_data_std = std_data.append(dummy_vars)

# # Print out the entire DataFrame. 
# print(student_data_std)

    math  reading  science Dummy Vars
0     90       82       90  [0, 0, 1]
1    100       73       92  [1, 0, 0]
2     80       92       95  [0, 0, 1]
3     95      100       82  [0, 1, 0]
4     90       79       81  [0, 1, 0]
5     90       90       90  [1, 0, 0]
6    100       89       91  [0, 0, 1]
7     80       85       79  [0, 0, 1]
8     85       99       85  [1, 0, 0]
9    100       73       92  [1, 0, 0]
10    80       92       95  [0, 0, 1]
11    95      100       82  [0, 1, 0]
12    90       79       81  [0, 1, 0]
13    86       92       90  [1, 0, 0]
14   100       89       89  [0, 0, 1]
15    83       95       79  [0, 0, 1]
    math  reading  science
0     90       82       90
1    100       73       92
2     80       92       95
3     95      100       82
4     90       79       81
5     90       90       90
6    100       89       91
7     80       85       79
8     85       99       85
9    100       73       92
10    80       92       95
11    95      100       82
12 

In [5]:
# Using a split ratio of 70:30, spit the student_data_1 into training and test set. 
# Reference the input and output of the training set as X_train and y_train respectively. 
# Reference the input and output of the test set as X_test and y_test respectively.
X = student_data_1.drop('science', axis = 'columns')
y = student_data_1.science

X_train = X[:11]
y_train = y[:11]
X_test = X[12:]
y_test = y[12:]

print(X_train)
print(y_train)
print(X_test)
print(y_test)

    math  reading Dummy Vars
0     90       82  [0, 0, 1]
1    100       73  [1, 0, 0]
2     80       92  [0, 0, 1]
3     95      100  [0, 1, 0]
4     90       79  [0, 1, 0]
5     90       90  [1, 0, 0]
6    100       89  [0, 0, 1]
7     80       85  [0, 0, 1]
8     85       99  [1, 0, 0]
9    100       73  [1, 0, 0]
10    80       92  [0, 0, 1]
0     90
1     92
2     95
3     82
4     81
5     90
6     91
7     79
8     85
9     92
10    95
Name: science, dtype: int64
    math  reading Dummy Vars
12    90       79  [0, 1, 0]
13    86       92  [1, 0, 0]
14   100       89  [0, 0, 1]
15    83       95  [0, 0, 1]
12    81
13    90
14    89
15    79
Name: science, dtype: int64


In [31]:
# Use the boston_1 DataFrame in question 1a, select the LowTemp, HighTemp, WarmestMin, ColdestHigh, AveMin, AveMax columns
# Use the “pipeline” functionality in sklearn to transform the selected data using the MinMaxScalar() & Imputer() classes.  
bostonData = combined_boston.drop(['Month', 'Year'], axis = 'columns')

# With the SimpleImputer() class, the missing data in each column should be imputed using the mean value for the column.
imp = SimpleImputer(missing_values = np.nan, strategy = "mean")
scaler = MinMaxScaler()
pipe = Pipeline([("impute", imp), ("scaler", scaler)])
pipeline_data = pipe.fit_transform(bostonData)

# Print the pipeline_data
print(pipeline_data)

# Output the descriptive statistics of the pipeline_data including mean, median, variance, minimum value, maximum value, 
# variance, standard deviation and skewness. You can use the .apply() functionality of the pandas DataFrame.
scipy.stats.describe(pipeline_data)

[[0.12345679 0.12698413 0.17857143 0.125      0.07479675 0.03993344]
 [0.13580247 0.19047619 0.125      0.18055556 0.20650407 0.12479201]
 [0.34567901 0.50793651 0.32142857 0.30555556 0.36747967 0.34775374]
 ...
 [0.7037037  0.65079365 0.60714286 0.68055556 0.6796748  0.59733777]
 [0.50617284 0.41269841 0.375      0.43055556 0.44878049 0.37271215]
 [0.44444444 0.38095238 0.30357143 0.36111111 0.40487805 0.27620632]]


DescribeResult(nobs=1140, minmax=(array([0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1.])), mean=array([0.59960372, 0.58755332, 0.52962018, 0.55377493, 0.58067372,
       0.53106228]), variance=array([0.05415836, 0.05829545, 0.05775097, 0.05848488, 0.06123414,
       0.07213077]), skewness=array([-0.17533383, -0.33477989, -0.13265523, -0.07365291, -0.06295492,
       -0.05675943]), kurtosis=array([-1.14860356, -1.11636826, -1.25430314, -1.16092836, -1.27216709,
       -1.3273628 ]))